#!/bin/bash
# /etc/init.d/my_boot
  
### BEGIN INIT INFO
# Provides: embbnux
# Required-Start: $remote_fs $syslog
# Required-Stop: $remote_fs $syslog
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
# Short-Description: my_boot initscript
# Description: This service for my_boot
### END INIT INFO
case "$1" in
    start):
        echo "Starting app"
	echo `date`:my boot start frpc >> /home/pi/boot.log
        killall frpc
	nohup /home/pi/bin/frpc -c /home/pi/frpc.ini >> /dev/null  & 
        ;;
    stop):
        echo "stop"
	killall frpc
        ;;
    *):
	    echo "Usage: $0 (start|stop)"
	    exit 1
	    ;;
esac

exit 0
